### ISSUE TITLE
(invalid) Storing email/password in MailSender.cs

### ISSUE THREAD

**Issue by DPelts** [cpvrlab/cpvr-vr-suite#5]
Is a security issue.
I suggest, you store the values in a seperate file (e.g. `Asset/Resources/Secrets/EmailLogin.json`) and load it when you want to send an E-Mail. This file can then be excluded by `.gitignore`. And please change the password afterwards.

**Comment by saschaledermann** [comment]
- Removed credentials from code.
- Replaced application password.
- Created json containing all relevant data for mail sending.
- JSON file needs to be added to each project using this package in `Asset/Resources/Secrets/EmailLogin.json`
